name: Deploy to Pages
on:
  push:
    branches:
      - master
    paths:
      - "vite.config.ts"
      - "src/**"
      - ".github/workflows/pages-deploy.yml"
jobs:
  build-and-deploy-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
          persist-credentials: false
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn run lint
      - name: Build
        run: yarn run build:demo
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: demo
          single-commit: true
